#!/usr/bin/env ruby
# frozen_string_literal: true

# require "pathname"
# $LOAD_PATH.unshift(Pathname(File.dirname(__FILE__)).parent.join("lib").expand_path.to_s)

require "sc2ai"
require "sc2ai/cli/cli"

# This got old quickly.
# puts <<-LOGO
#
#         .:^~!77?7~:.          .:~7?77!~^:.
#         .:~?JYJJJJJJ?7~.  .!7JJJJJJJYJ?~:
#             .^?JJJJJJJY:  ^YJJJJJJJ?^.
#                7JJJJJJJ.  ^JJJJJJJ7
#       .^^^^^^^^YPPPPPPP?. :JJ55555?.:::::::::::.
#      7@@@@@@@@@@@@@&&@&J  ^G#&&&&&@@@@@@@@@@&G!.
#      ^77!!!!!!!PGGB&&BY.  !BGGGGGGP77777?BG7.
#        ~??777?~7JJJYYJJ: !PBBBBBYJ~
#         J&@@@@@&PJJJJJJ..&@&&&&&YJ~    ~PGJ   JG?
#          .Y&@&&&&#YJJJJ.!@&&&&&&JJ~  .#P @@!  &@#
#            .P&&&&&&GJJJ.^@&&&&&&YJ~  @#G77@@. #@#
#              ^B&&&&&&PJ. B@&&&&&BJ~ 7@J.: :@B #@5
#        ~:      Y&&&&&&#^ .B@&&&&&#!         . :J
#      7#@&BPPPPPB&&&&&&&&! ^B&&&&&&&5~.
#   .J&@&&&&&&&&&&&&&&&&&&! :JYP#&&&&@@&&B5^
#   .:...........?5555555^  ^JJJJY5PJ^^:.
#                .JJJJJJJ:  ^JJJJJJJ.
#                 .!JJJJJ:  ^JJJJJ!
#                   .!JJY:  ^YJJ~.
#                      :7.  :7:
#
# LOGO

Sc2::Cli.start
